# Generated by Django 3.2.5 on 2021-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=999),
        ),
    ]
